lab check
created-by-pavel/ITMO_OOP pull request #1
Opened 2021-09-12 09:02 UTC by created-by-pavel

2021-09-13 13:41 UTC, xrem commented on Isu.Tests/IsuServiceTest.cs
> +            var isu = new IsuService();
Инициализацию объекта тестирования нужно перенести в метод `Setup()`

2021-09-13 13:42 UTC, xrem commented on .idea/.idea.OopLabs/.idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Служебные файлы Rider'a не нужно коммитить, добавь их в .gitignore

2021-09-13 13:42 UTC, xrem commented on Isu.Tests/IsuServiceTest.cs
>          public void TransferStudentToAnotherGroup_GroupChanged()
Судя по неймингу тест должен пройти, а у тебя ожидается исключение

2021-09-13 13:44 UTC, xrem commented on Isu/Models/Group.cs
> +            private short _studentsCount;
studentsCount может быть автогенерённым полем => (short) this._students.Length;

2021-09-13 13:52 UTC, xrem commented on Isu/Models/Group.cs
> +                int num = groupName[2] - '0';
Ты свои грязные хаки из плюсов сюда не тащи :)
либо `int.Parse()` либо `int.TryParse()`

2021-09-13 13:53 UTC, xrem commented on Isu/Models/Group.cs
> +                if (_students.Contains(student))
Для того чтобы так сравнивать, нужно либо написать свой компаратор и передать его сюда, либо реализовать IEquatable<Student>

2021-09-13 13:55 UTC, xrem commented on Isu/Services/IsuService.cs
> +                if (name.Length > 6 || name[0] != 'M' || name[1] != '3' || (int.TryParse(sub, out n) == false))
```suggestion
                if (name.Length != 5 || !name.BeginsWith("M3") || !int.TryParse(sub, out n))
```

2021-09-13 13:56 UTC, xrem commented on Isu/Services/IsuService.cs
> +                    if (group.GetGroupName() == groupName)
Вместо foreach'a можно просто взять групу по названию.
_groups.FirstOrDefault(g => g.GetGroupName() == groupName)

2021-09-13 13:58 UTC, xrem commented on Isu/Services/IsuService.cs
> +                        return group.GetByGroupName();
Нейминг метода страдает.
Get**Что-то**By**Фильтр** 
т.е. фильтра нет, то предлагаю просто GetStudentList() или просто GetStudents()

2021-09-13 14:00 UTC, xrem requested changes
Нужно поправить замечания, передалать foreach'ы на LINQ

2021-09-13 17:41 UTC, created-by-pavel commented on Isu.Tests/IsuServiceTest.cs
>          public void TransferStudentToAnotherGroup_GroupChanged()
в шаблоне изначально написано, что ожидается исключение. Я, как прилежный студент, и задал такую группу, чтоб оно вызвалось)

2021-09-16 23:41 UTC, xrem commented on Isu.Tests/IsuServiceTest.cs
>          public void TransferStudentToAnotherGroup_GroupChanged()
Это был пранк от Fredi, поменяй название тестового метода.

2021-09-16 23:42 UTC, xrem commented
>created-by-pavel requested a review from xrem 2 days ago
но... Файлы от райдера всё ещё в PR'e.
Перечитай закреплённое сообщение в общем телеграмм канале, поправь замечания и переводи project снова в очередь

2021-09-16 23:43 UTC, xrem requested changes
Ожидаю резолва всех замечаний

2021-09-17 18:37 UTC, xrem commented on Isu.Tests/Isu.Tests.csproj
> -<Project Sdk="Microsoft.NET.Sdk">
А тебя не смутило ничего когда ты файл с проектом зачистил?
Ну например то что build падает?

2021-09-17 18:38 UTC, xrem commented on Isu.Tests/IsuServiceTest.cs
> +
Reduntant whitespaces (поправь по всему проекту пожалуйста)

2021-09-17 18:41 UTC, xrem commented on Isu.Tests/IsuServiceTest.cs
> +            try
вместо блока try{}catch{} нужен Assert.Catch из nunit'a

2021-09-17 18:42 UTC, xrem commented on Isu/Models/Group.cs
> +                if (_groupName == other._groupName)
а почему нельзя просто `return _groupName == other._groupName` ? :)

2021-09-17 19:26 UTC, xrem commented on Isu/Models/Group.cs
> +                return (_groupName, _courseNum).GetHashCode();
Нужно заксорить hashCode'ы полей, так как ты сделал не совсем корректно может сработать.
см. https://stackoverflow.com/questions/1008633/gethashcode-problem-using-xor

2021-09-17 19:34 UTC, xrem commented on Isu/Services/IsuService.cs
> +                if (name.Length != 5 || !name.StartsWith("M3") || !int.TryParse(sub, out n))
int n; c 17-ой строчки можно заинлайнить
```suggestion
                if (name.Length != 5 || !name.StartsWith("M3") || !int.TryParse(sub, out var n))
```

2021-09-17 19:36 UTC, xrem commented on Isu/Models/Group.cs
> +            public List<Student> GetStudents() => _students;
Тут лучше копию отдавать, чтобы не получилось что я могу мутировать настоящую коллекцию снаружи

2021-09-17 19:37 UTC, xrem commented on Isu/Services/IsuService.cs
> +                return st;
```suggestion
                return _groups.FirstOrDefault(group => group.GetByName(name) != null)
```

2021-09-17 19:37 UTC, xrem commented on Isu/Services/IsuService.cs
> +                var st = new Student();
Если ничего не найдется, то наверно нужно отдать null, а не студента без всего

2021-09-17 19:38 UTC, xrem commented on Isu/Services/IsuService.cs
> +                return group?.GetStudents();
```suggestion
                return group?.GetStudents() ?? new Enumerable.Empty<Student>.ToList();
```

2021-09-17 19:38 UTC, xrem commented on Isu/Services/IsuService.cs
> +                foreach (Group group in _groups)
Будет круто если получится переписать с использованием LINQ без foreach'a

2021-09-17 23:34 UTC, created-by-pavel commented on Isu/Services/IsuService.cs
> +                foreach (Group group in _groups)
я считаю, что если бы я написал LINQ в этом методе вместо foreach'а, то он бы получился 
1)достаточно длинный 
2)сложный в понимании
3)сложный в написании 
4)в notion 'e использовать linq вместо foreach'a помечено как suggestion, не do, поэтому я и использую простые короткие LINQ запросы который просты в написании

2021-09-18 07:23 UTC, xrem approved these changes
Принято

2021-09-18 07:31 UTC, merged